# Generated by Django 3.1.2 on 2020-11-14 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_tracker_tbl',
            fields=[
                ('food_id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='food item id')),
                ('food_date', models.DateTimeField(verbose_name='food item date')),
                ('food_name', models.TextField(max_length='200', verbose_name='food item name')),
                ('food_weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='food weight')),
                ('food_calories', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='food calories')),
                ('food_carbohydrates', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='food carbohydrates')),
                ('food_protein', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='food protein')),
                ('food_fat', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='food fat')),
            ],
        ),
    ]
