# Generated by Django 3.1.2 on 2020-11-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='body_stats_tbl',
            fields=[
                ('bs_entry_id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='body stat entry id')),
                ('bs_date', models.DateTimeField(verbose_name='Body stat date')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='body height')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='body weight')),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='body bmi')),
            ],
        ),
    ]
