# Generated by Django 3.1.2 on 2020-11-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyStats', '0002_body_stats_tbl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body_stats_tbl',
            name='bmi',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='body_stats_tbl',
            name='bs_date',
            field=models.DateTimeField(verbose_name='Date Recorded'),
        ),
        migrations.AlterField(
            model_name='body_stats_tbl',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='body_stats_tbl',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight'),
        ),
    ]
