# Generated by Django 3.1.2 on 2020-11-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyStats', '0003_auto_20201117_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body_stats_tbl',
            name='bs_date',
            field=models.DateField(verbose_name='Date Recorded'),
        ),
    ]
