# Generated by Django 3.1.2 on 2020-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyStats', '0004_auto_20201118_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body_stats_tbl',
            name='bs_date',
            field=models.DateTimeField(verbose_name='Date Recorded'),
        ),
    ]
