# Generated by Django 3.1.2 on 2020-12-10 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyStats', '0007_auto_20201209_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body_stats_tbl',
            name='bs_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Recorded'),
        ),
        migrations.AlterField(
            model_name='body_stats_tbl',
            name='bs_entry_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='body stat entry id'),
        ),
    ]
