# Generated by Django 3.1.2 on 2020-12-02 20:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='food_tbl',
            fields=[
                ('food_entry_id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='food entry id')),
                ('food_date', models.DateTimeField(verbose_name='date recorded')),
                ('food_name', models.TextField(verbose_name='food name')),
                ('food_calories', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)], verbose_name='food calories')),
                ('food_weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)], verbose_name='food weight')),
                ('food_fat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)], verbose_name='food fat')),
                ('food_protein', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)], verbose_name='fod protein')),
                ('food_carbohydrates', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)], verbose_name='food carbohydrates')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
