# Generated by Django 3.1.2 on 2020-12-09 09:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_tbl',
            name='food_entry_id',
            field=models.AutoField(db_index=True, default=datetime.datetime.now, primary_key=True, serialize=False, unique=True, verbose_name='food entry id'),
        ),
        migrations.AlterField(
            model_name='food_tbl',
            name='food_protein',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)], verbose_name='food protein'),
        ),
    ]
