# Generated by Django 3.1.2 on 2020-12-10 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20201209_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_tbl',
            name='food_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date recorded'),
        ),
    ]
