# Generated by Django 3.1.2 on 2020-11-14 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='exercise_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('bench press', 'Bench Press'), ('sit ups', 'Sit Ups'), ('biceps', 'Biceps')], default='Cardio', max_length=100),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
