# Generated by Django 3.1.2 on 2020-11-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20201114_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='exercise_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('bench press', 'Bench Press'), ('sit ups', 'Sit Ups'), ('biceps', 'Biceps'), ('other', 'Other')], default='Cardio', max_length=100),
        ),
    ]
